require("user.launch")
require("user.options")
require("user.keymaps")
require("user.autocmds")

spec("user.plugins.ui")
spec("user.plugins.extras")
spec("user.plugins.copilot")
spec("user.plugins.git")
spec("user.plugins.treesitter")
spec("user.plugins.telescope")
spec("user.plugins.lsp")
spec("user.plugins.cmp")

require("user.lazy")
